export { default as AnimeSection } from "./AnimeSection";
export { default as GenreSection } from "./GenreSection";
export { default as Popular } from "./Popular";
export { default as Movies } from "./Movies";
export { default as TopAiring } from "./TopAiring";
export { default as RecentRelease } from "./RecentRelease";
export { default as GenreAnime } from "./GenreAnime";
export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
