export {default as AnimeSection } from './AnimeSection'
export {default as GenreSection} from './GenreSection'
export {default as Popular} from './Popular'
export {default as Movies} from './Movies'
export {default as TopAiring} from './TopAiring'